#!/bin/bash
Username=$USERNAME
Date=`(date +%c)`
Hostname=$HOSTNAME
source /etc/os-release
OS=$PRETTY_NAME
Uptime=`(uptime -p)`
cat << EOF

System Report generated by, $Username, $Date

System Information
------------------------------
Hostname: $Hostname
OS:$OS
Uptime: $Uptime


Hardware Information
------------------------------
CPU:$(lscpu -C)


EOF
