#!/bin/bash
Username=$USERNAME
Date=`(date +%c)`
Hostname=$HOSTNAME
source /etc/os-release
OS=$PRETTY_NAME
Uptime=`(uptime -p)`
CPU=`(lscpu | grep 'Model name:' | awk -F':' '{print $2}' | xargs)`
Speed=`(cat /proc/cpuinfo | grep 'MHz' | uniq)`
RAM=`(lscpu | grep MemTotal /proc/meminfo | awk '{print $2, "kB"}' )`
Disk=`(lsblk | grep 'disk')`
Video=`(lspci -vnn | grep -i vga | cut -d ':' -f3- | cut -c1-24)`



cat << EOF


System Report generated by, $Username, $Date

System Information
------------------------------
Hostname: $Hostname
OS: $OS
Uptime: $Uptime


Hardware Information
------------------------------
CPU: $CPU
Speed:$Speed
RAM:$RAM
Disk(s):$Disk
Video Card:$Video


EOF
